### ISSUE TITLE
Static builds

### ISSUE THREAD

**Issue by namandixit** [mmozeiko/build-sdl3#5]
Would it be possible to add static builds of the libraries too along with the dynamically linked ones?

**Comment by mmozeiko** [comment]
Static libraries on Windows are tricky.

They very much depend on build settings. Otherwise they may not work with your build. For example - typical /MT vs /MD vs /MTd vs /MDd setting. That's like already 4 variants (well at least 2 if only release builds) I would need to do.

Other reason - VS version. Do you use 2015, 2017, 2019, 2022? Which minor version of 2022? Technically cl.exe is backwards and forwards compatible, but linker is not. Linker is guaranteed only to be backwards compatible, cannot link obj's with older linker than cl was used to produce them - see https://learn.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170

So it's just a lot extra maintenance or extra builds to do to produce static libs that would be useful to others. Currently I recommend modifying build.cmd for your specific use case and running such build locally.
